export const ApiErrorCode = {
  // 인증 & 권한 (4xx)
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // 검증 오류
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_PARAMETER: "INVALID_PARAMETER",

  // 비즈니스 로직 오류 (4xx)
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  GONE: "GONE",
  UNPROCESSABLE: "UNPROCESSABLE",
  RATE_LIMITED: "RATE_LIMITED",
  INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
  PLAN_LIMIT_EXCEEDED: "PLAN_LIMIT_EXCEEDED",
  RESOURCE_LOCKED: "RESOURCE_LOCKED",

  // 의존성 오류 (5xx)
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",

  // 일반 오류 (5xx)
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
